### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by sambrasil** [sambrasil/Video_maker#1]
- [ ] Criar a lista com um resumo das atividades a serem implementadas nesse projeto
---
- [ ]  Orquestrador
  - [x] Perguntar pelo termo de busca
  - [x] Perguntar pelo prefixo
  - [x] iniciar robô de texto
  - [ ] iniciar robô de imagens
  - [ ] iniciar robô de videos
  - [ ] iniciar robô do youtube
---
- [ ] Robô de texto
   - [x] Estrutura de dados
   - [x] Pegar conteúdo da Wikipedia
   - [x] Limpar conteúdo
   - [x] Quebrar em sentenças
   - [ ] Pegar a interpretação do Watson
   - [ ] Adicionar tags
   - [ ] Salvar estrutura de dados
